name: jira-dispatch

on:
  workflow_dispatch:
    inputs:
      jira_issue_key:
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "jira_issue_key=${{ inputs.jira_issue_key }}"
